version: "3.9"  # optional since v1.27.0
services:
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_DB_CONNECTION_STRING=mongodb+srv://Asma5577:Ak/01631172276@cluster0.u0e5rgd.mongodb.net/?retryWrites=true&w=majority
      - MONGO_DB_NAME=cluster0
      - REDIS_URI=redis://host.docker.internal:6379
      